"""remove reel_comments table and feature

Revision ID: 2b3dd6c56674
Revises: 6d82e6ac58e5
Create Date: 2026-09-12 14:54:26.509521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3dd6c56674'
down_revision = '6d82e6ac58e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_comments_reel_id'))
        batch_op.drop_index(batch_op.f('ix_reel_comments_user_id'))

    op.drop_table('reel_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reel_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_comments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reel_comments_reel_id'), ['reel_id'], unique=False)

    # ### end Alembic commands ###
