"""add index on products.views

Revision ID: 789fa42b8b7c
Revises: d4e5f6a7b8c9
Create Date: 2026-09-12 02:43:47.133868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789fa42b8b7c'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_views'), ['views'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_views'))
    # ### end Alembic commands ###
