"""add last_seen to users

Revision ID: 9315065eaac3
Revises: 9bfb6bc2028e
Create Date: 2026-09-09 17:09:12.444796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9315065eaac3'
down_revision = '9bfb6bc2028e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_last_seen'), ['last_seen'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_last_seen'))
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
